### ISSUE TITLE
mirrorlist

### ISSUE THREAD

**Issue by udeved** [cromnix/packages#1]
The idea with the SF mirrors doesn't work out unfortunately.
The url is invalid, only seems to work with direct file links.

**Comment by cromerc** [comment]
So only the first mirror works but not the rest I assume?

**Comment by udeved** [comment]
Yep, too bad.
Not sure the long referral link is of any use or reproducible, usable.

**Comment by cromerc** [comment]
Join me on irc, I am setting up the keyring.

**Comment by cromerc** [comment]
From the looks of it, those mirrors are not automatic, they do have support for manjaro, debian, ubuntu, and arch linux for example, but Cromnix is not mirrored by them:
https://heanet.dl.sourceforge.net/mirrors/
That's why it doesn't work for us, they don't mirror cromnix currently.

We  will need to get some sponsored mirrors to help with the project. But for the time being only the default sourceforge one is working.

**Comment by udeved** [comment]
Could we redirect SF in the SF options to at least a second account to have one backup url for pacman?

**Comment by cromerc** [comment]
That wouldn't really solve anything because if SF goes down, both accounts/urls would be dead.

**Comment by udeved** [comment]
Would your uni eventually provide you with webspace?

I thinking to get away from SF hosting. Its unreliable.

For example UK Kent uni offer a mirror service.

https://www.mirrorservice.org/

or other unis offer also mirror services

http://www.knopper.net/knoppix-mirrors/

**Comment by cromerc** [comment]
I hope so. One of my professors said he was going to look into whether or not the uni could provide something like that. Currently my uni does not host any linux mirrors/repos. Hopefully they will do it.

**Comment by cromerc** [comment]
I have sent an email to the head of the IT department of the university asking about the possibility of hosting a mirror. Now to wait and see what they say.

**Comment by udeved** [comment]
Nice, I think as student, you could also email other unis and ask if cromnix could be mirrored.
Usually, the only precondition is being a student, at least in Germany.

**Comment by cromerc** [comment]
I just got a response. They have an extra server that they can let me use. I have to go and check out the server and see if it fits our needs. Looks like the server would be dedicated to our project for the moment since at the moment it isn't being used. They asked me which OS I want to install in the server, lol. Maybe if the server is nice enough it could be used as a build server as a bot?

**Comment by udeved** [comment]
Sounds very nice. :)
 I'd first make it host the repo stuff to be accessible as our build url. If it has enough capacity, we may use it as buildserver.

**Comment by cromerc** [comment]
Well I will know more later. At 11:00 my time I am scheduled to go see and review the server.

**Comment by cromerc** [comment]
Well I am setting up the server. The university provided me with a dell rackserver.
Specs are nice:
2 xenon processors, each with dual core at 2.8ghz
8GB of RAM
Raid controller with 2 channels with 6 disks:
4 x 300GB
2 x 73GB
2 Gigabit lan connectors
I just finished setting up 2 raids, raid 0 on the 2 73GB drives for speed for the OS, and raid 5 on the 4 300GB disks for parity and backup purposes.
I am going to install debian on it as it's primary OS, I am burning the iso to my pen drive now.
