### ISSUE TITLE
pam rebuilds?

### ISSUE THREAD

**Issue by udeved** [cromnix/packages#4]
I think we should merge pam in master branch next to start work on ck and elogind. @cromerc 

We perhaps also start working in testing branch so merges in master won't produce conflicts much.

**Comment by cromerc** [comment]
I agree with the working in a different branch to avoid conflicts from merges. I think what we should do is that when we work on packages, make a new branch, do our work, then do a pull request from the new branch into master. That way during the PR it would show us any conflicts so that we can fix them and the master branch won't get messed up.

As far as pam, are you building it now? If so I will leave that to you while I work on something for the OpenRC init system. I am going to create the pacman hooks that will setup OpenRC as the init when cromnix is installed/pacstrapped.

**Comment by cromerc** [comment]
I found some configuration options for branches in github which I just activated. Pushing to master is now disabled, the only way to update master is to use PR. I also set it so that a PR can only be merged into master if the other branch is up to date, so if the latest updates are not in the testing branch in the PR it cannot be merged. It also requires that the PR be reviewed and approved before the merge is actually done into master, this way master should stay clean of any conflicts.
With these options I believe we should be fine and not accidentally overwrite each other's work.

As I mentioned, in the previous post, I think working from a "cromer" and "artoo" branch will be fine, then we just PR our changes to master once we are ready.

**Comment by udeved** [comment]
Sound good.
Lets do it that way.
I will do pam in artoo branch along with elogind stuff.

I think we should decide what default session tracker we use. Since there is no ck feature parity with elogind, I would opt for elogind default. Its propably also better supported by upstream by now. NM has elogind support for example, udisks2 too.

Not sure I have got time to build them, but I can prepare it all for building.

**Comment by cromerc** [comment]
For the default session tracker, elogind will be fine, I especially want elogind because with it we can get plymouth working with a pretty boot screen and OpenRC.

As far as the building goes, when your PR gets merged into master I will build it all.

**Comment by udeved** [comment]
I will add also sddm, which means qt5-base package too.
Do we want to take the rest of qt5 from arch?

**Comment by cromerc** [comment]
No, I want to start on qt5 officially instead of pulling from arch. I want to build lxqt which means I need to get qt5 done properly. I am going to do qt5 and lxqt during next week.

What is your onion between lxde and lxqt? I believe that our lightweight DE should be one of these, however I have not decided on which one.

**Comment by udeved** [comment]
Ì was gonna say, my next step would have been adding lxqt. which thends to be workig better with elogind. The openrc-settingsd provides the systemd locale and time stuff, but not sure if its uptodate.
Once we got this going, I will install cromnix, and can add kde from arch.

**Comment by udeved** [comment]
@cromerc 

I am going to split out libeudev, which comes in handy later for xorg drivers, that only require libudev, bot full udev package. elogind will be similar, libelogind split out, so we can add both libs to the cromix-dev group.

**Comment by cromerc** [comment]
Have a look at the atk PKGBUILD: https://github.com/cromnix/packages/blob/master/main/atk/PKGBUILD

This is my goal for the cromnix packages. So for example there would be eudev, libeudev, eudev-dev, and eudev-doc packages after the split. The eudev-dev is a dependency that is only needed in makedepends, normal users do not need development headers since they don't usually compile code. All a standard user needs is the libs, binaries, and docs.

So for example when I made the lxde packages you will notice that they have depends=atk and makedepends=atk-dev

For example in my arch linux install I have 1GB worth of development headers installed that I don't even use since I do all my compiling in a chroot anyway. The idea is that we can shave off a lot of storage space requirements for things like raspberry pi or other similar projects by splitting the packages up.

**Comment by udeved** [comment]
Thats fine, I am familiar with the concept  of dev packages from debian based linux.
But, lets do this a little later, I first want to make sure depends are properly set. Splitting out headers would be next step we should do, I think.
